# Generated by Django 4.2.7 on 2023-11-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ile',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
