# Generated by Django 4.2.7 on 2023-11-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody_web', '0002_remove_article_ile_article_title_article_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='year',
            new_name='rok',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='drzwi',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='marka',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='model',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='naped',
            field=models.CharField(choices=[('przedninaped', 'Przedni napęd'), ('tylnaped', 'Tylni naped'), ('4x4', 'Napęd 4x4')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='silnik',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='skrzynia_biegów',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
