# Generated by Django 4.2.7 on 2023-11-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody_web', '0003_rename_year_article_rok_remove_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='drzwi',
            field=models.IntegerField(),
        ),
    ]
